export default {
  values: {
    socBMS: undefined,
    chargebits: undefined,
    dcCurrent: undefined,
    dcVoltage: undefined,
    batMaxTemp: undefined,
    batMinTemp: undefined,
    batModule01Temp: undefined,
    batModule02Temp: undefined,
    batModule03Temp: undefined,
    batModule04Temp: undefined,
    batModule05Temp: undefined,
    batInletTemp: undefined,
    maxCellVoltage: undefined,
    maxCellVoltageNo: undefined,
    minCellVoltage: undefined,
    minCellVoltageNo: undefined,
    fanStatus: undefined,
    fanSpeed: undefined,
    auxBatteryVoltage: undefined,
    cumulativeChargeEnergy: undefined,
    cumulativeDischargeEnergy: undefined,
    cumulativeOperatingTimeHours: undefined,
    batModule06Temp: undefined,
    batModule07Temp: undefined,
    batModule08Temp: undefined,
    batModule09Temp: undefined,
    batModule10Temp: undefined,
    batModule11Temp: undefined,
    batModule12Temp: undefined,
    soh: undefined,
    socDisplay: undefined,
  },
}
